Пишет функции дз2
htmlacademy-javascript/1224279-kekstagram-25 pull request #2
Opened 2022-02-20 19:43 UTC by potapov11

2022-02-21 18:35 UTC, Finnko requested changes

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +function randomNumber(min, max) {
По [критерию](https://up.htmlacademy.ru/javascript/25/criteries#d5) нужно единообразие функций, потом большая часть будет стрелочными, поэтому сразу давай придерживаться того, что все функции на проекте будут стрелочными

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +function randomNumber(min, max) {
По другому критерию в названии функции всегда должен присутствовать глагол

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +  if (min <= 0 ) {
Так же следует проверять случай когда минимум больше или равен максимуму

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +    const ALERT_MESSAGE= 'Передайте номер больше 0 для min';
Константы используемые внутри функций должны использоваться по замыканию. Для этого объявление ALERT_MESSAGE следует поднять выше

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +    return ALERT_MESSAGE;
Давай будем не просто объявлять строку, но и воспользуемся конструкцией throw new Error('текст ошибки') чтобы выбросить исключение и остановить выполнение программы

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +  const INNER_NUMBER = Math.random()*(max-min) + min;
Константа это когда мы знаем значение до начала исполнения кода и во время исполнения оно не меняется, здесь у тебя обычная переменная можно назвать ее rand(om)

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +  const INNER_NUMBER = Math.random()*(max-min) + min;
Вокруг операндов надо ставить всегда пробелы, следи за этим
```suggestion
  const INNER_NUMBER = Math.random() * (max - min) + min;
```

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +const MAX_LENGTH = 30;
Вроде по условию макс длина 140? И само объявление константы по Б5 надо поднять в самое начало файла.

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +function isStringLength(a) {
Твой вариант абсолютно правильный, но для строки обычно используется сокращение str. Так просто будет понятней твоим будущим коллегам
```suggestion
function isStringLength(str) {
```

2022-02-21 18:35 UTC, Finnko commented on js/main.js
> +// имя_функции(проверяемая_строка, максимальная_длина); // Результат: true, если строка проходит по длине, и false — если не проходит
Твоя функция должна иметь интерфейс вызова вида isStringLength('efwefwefweff', MAX_LENGTH). Надо поправить функцию

2022-02-21 19:29 UTC, potapov11 commented on js/main.js
> +  if (min <= 0 ) {
Можно так? if (min <= 0 || min => max) {...}

2022-02-21 19:37 UTC, Finnko commented on js/main.js
> +  if (min <= 0 ) {
Да, конечно, и таким образом нам не надо покрывать вариант когда max < 0, эти условия его уже покрывают

2022-02-22 19:32 UTC, Finnko requested changes

2022-02-22 19:32 UTC, Finnko commented on js/main.js
> +  const INNER_NUMBER = Math.random() * (max-min) + min;
Почему эта переменная константым синтаксисом?)

2022-02-23 18:22 UTC, Finnko approved these changes

2022-02-23 18:22 UTC, merged